SuperCars/Models/ErrorViewModel.cs
namespace SuperCars.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SuperCars/Models/Supercars.cs
namespace cars;
public class Scars{
    public String Brand{get;set;}
    public String Name{get;set;}
    public String Model{get;set;}
    public String Price{get;set;}
}

SuperCars/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SuperCars.Models;

namespace SuperCars.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SuperCars/Controllers/ScarsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SuperCars.Models;
using cars;
namespace SuperCars.Controllers;

public class ScarsController : Controller
{
    private readonly ILogger<ScarsController> _logger;

    public ScarsController(ILogger<ScarsController> logger)
    {
        _logger = logger;
    }

    public IActionResult Scars()
    {
        Scars sc = new Scars();
        sc.Brand = "Pagani";
        sc.Name="Zonda";
        sc.Model="PZ-6969";
        sc.Price ="$ 1,500,000";
        ViewData["Cars"] = sc;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SuperCars/Views/Scars/Scars.cshtml
@using cars;

@{
    ViewData["Title"] ="SUPER CARS";
}

<div>
<head>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
@{
    Scars sc = ViewData["Cars"] as Scars;
}

<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/images/pagani.jpeg" class="d-block w-100" alt="...">
        <p>Brand :@sc.Brand </p>
        <p>Name :@sc.Name </p>
        <p>Model :@sc.Model </p>
        <p>Price :@sc.Price </p>
    </div>
    <div class="carousel-item">
      <img src="/images/pagani.jpeg" class="d-block w-100" alt="...">
        <p>Brand :@sc.Brand </p>
        <p>Name :@sc.Name </p>
        <p>Model :@sc.Model </p>
        <p>Price :@sc.Price </p>
    </div>
    <div class="carousel-item">
      <img src="/images/pagani.jpeg" class="d-block w-100" alt="...">
        <p>Brand :@sc.Brand </p>
        <p>Name :@sc.Name </p>
        <p>Model :@sc.Model </p>
        <p>Price :@sc.Price </p>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>

SuperCars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperCars</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperCars.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperCars</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scars" asp-action="Scars">SuperCars</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SuperCars - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>